# Generated by Django 6.0.6 on 2026-06-29 16:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Libro',
            fields=[
                ('isbn', models.CharField(max_length=13, primary_key=True, serialize=False, verbose_name='ISBN')),
                ('titulo', models.CharField(max_length=255, verbose_name='Título')),
                ('autor', models.CharField(max_length=255, verbose_name='Autor')),
                ('cantidad_total', models.PositiveIntegerField(default=1, verbose_name='Cantidad Total')),
                ('tarifa_diaria', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Tarifa Diaria')),
            ],
        ),
        migrations.CreateModel(
            name='Miembro',
            fields=[
                ('miembro_id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID Miembro')),
                ('nombre_completo', models.CharField(max_length=255, verbose_name='Nombre Completo')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('telefono', models.CharField(blank=True, max_length=20, verbose_name='Teléfono')),
            ],
        ),
        migrations.CreateModel(
            name='Prestamo',
            fields=[
                ('prestamo_id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID Préstamo')),
                ('fecha_salida', models.DateField(auto_now_add=True, verbose_name='Fecha de Salida')),
                ('fecha_vence', models.DateField(verbose_name='Fecha de Vencimiento')),
                ('fecha_dev_real', models.DateField(blank=True, null=True, verbose_name='Fecha de Devolución Real')),
                ('costo_calculado', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Costo Calculado')),
                ('estado_transaccion', models.CharField(choices=[('Pendiente', 'Pendiente'), ('Pagado', 'Pagado'), ('Vencido', 'Vencido')], default='Pendiente', max_length=20, verbose_name='Estado de Transacción')),
                ('libro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='biblioteca.libro', verbose_name='Libro')),
                ('miembro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='biblioteca.miembro', verbose_name='Miembro')),
            ],
        ),
    ]
